### ISSUE TITLE
FitBounds + takescreen results in corrupted Image.

### ISSUE THREAD

**Issue by Daddelion** [grinat/leaflet-simple-map-screenshoter#27]
As you can see. When I execute map.fitBounds(layer.getBounds()). This is the resulting Image.

![git](https://user-images.githubusercontent.com/23214135/129119975-25ff7906-a1cd-40bb-9567-2cc2f3939c8c.png)

Is this a waiting issue?
I tried waiting for "zoomend" but that didn't help.

**Comment by grinat** [comment]
@Daddelion I think the problem is in the layout. Try to remove/change some css properties. For exam: https://github.com/grinat/leaflet-simple-map-screenshoter/issues/24#issuecomment-881563764

**Comment by Daddelion** [comment]
I don't really think so. I believe this happens, because it is noch finished with the panning/zooming. When I put the takescreen on a separate button instead of the same function. It works. But I cannot get the takescreen function to wait.

**Comment by Daddelion** [comment]
Here look at this jsfiddle:
https://jsfiddle.net/uk3nfegb/11/
1. draw a Polygon
2. press the button on top.
3. scroll down to see the image

**Comment by grinat** [comment]
@Daddelion fixed in 0.4.5

**Comment by Daddelion** [comment]
1. when it zooms it does not wait for the tiles to reload so it really lucks not good.
![image](https://user-images.githubusercontent.com/23214135/130812392-bac52502-5107-4fae-a0a7-445530a04e72.png)

2. sadly when it does a larger zoom, from zoom 3-10 sometime still happens, but its hard to reproduce :/ sorry
![image](https://user-images.githubusercontent.com/23214135/130811656-2c945bb5-a6d1-49ef-b854-82cf2068d523.png)


https://jsfiddle.net/458xac6m/
1. draw a  SMALL Polygon (so it zooms a lot)
2. press the button on top.
3. scroll down to see the image
